model = dict(
    type='PSGMaskFormer',
    backbone=dict(
        type='ResNet',
        depth=50,
        num_stages=4,
        out_indices=(0, 1, 2, 3),
        frozen_stages=-1,
        norm_cfg=dict(type='BN', requires_grad=False),
        norm_eval=True,
        style='pytorch',
        init_cfg=dict(type='Pretrained', checkpoint='torchvision://resnet50')),
    bbox_head=dict(
        type='PSGMaskFormerHead',
        in_channels=[256, 512, 1024, 2048],
        feat_channels=256,
        out_channels=256,
        num_classes=133,
        num_relations=56,
        num_queries=100,
        pixel_decoder=dict(
            type='TransformerEncoderPixelDecoder',
            norm_cfg=dict(type='GN', num_groups=32),
            act_cfg=dict(type='ReLU'),
            encoder=dict(
                type='DetrTransformerEncoder',
                num_layers=6,
                transformerlayers=dict(
                    type='BaseTransformerLayer',
                    attn_cfgs=dict(
                        type='MultiheadAttention',
                        embed_dims=256,
                        num_heads=8,
                        attn_drop=0.1,
                        proj_drop=0.1,
                        dropout_layer=None,
                        batch_first=False),
                    ffn_cfgs=dict(
                        embed_dims=256,
                        feedforward_channels=2048,
                        num_fcs=2,
                        act_cfg=dict(type='ReLU', inplace=True),
                        ffn_drop=0.1,
                        dropout_layer=None,
                        add_identity=True),
                    operation_order=('self_attn', 'norm', 'ffn', 'norm'),
                    norm_cfg=dict(type='LN'),
                    init_cfg=None,
                    batch_first=False),
                init_cfg=None),
            positional_encoding=dict(
                type='SinePositionalEncoding', num_feats=128, normalize=True)),
        enforce_decoder_input_project=False,
        positional_encoding=dict(
            type='SinePositionalEncoding', num_feats=128, normalize=True),
        transformer_decoder=dict(
            type='DetrTransformerDecoder',
            return_intermediate=True,
            num_layers=6,
            transformerlayers=dict(
                type='DetrTransformerDecoderLayer',
                attn_cfgs=dict(
                    type='MultiheadAttention',
                    embed_dims=256,
                    num_heads=8,
                    attn_drop=0.1,
                    proj_drop=0.1,
                    dropout_layer=None,
                    batch_first=False),
                ffn_cfgs=dict(
                    embed_dims=256,
                    feedforward_channels=2048,
                    num_fcs=2,
                    act_cfg=dict(type='ReLU', inplace=True),
                    ffn_drop=0.1,
                    dropout_layer=None,
                    add_identity=True),
                feedforward_channels=2048,
                operation_order=('self_attn', 'norm', 'cross_attn', 'norm',
                                 'ffn', 'norm')),
            init_cfg=None),
        sub_loss_cls=dict(type='CrossEntropyLoss',
                          use_sigmoid=False,
                          loss_weight=1.0,
                          class_weight=1.0),
        sub_loss_bbox=dict(type='L1Loss', loss_weight=5.0),
        sub_loss_iou=dict(type='GIoULoss', loss_weight=2.0),
        sub_loss_focal=dict(type='BCEFocalLoss', loss_weight=1.0),
        sub_loss_dice=dict(type='psgtrDiceLoss', loss_weight=1.0),
        obj_loss_cls=dict(type='CrossEntropyLoss',
                          use_sigmoid=False,
                          loss_weight=1.0,
                          class_weight=1.0),
        obj_loss_bbox=dict(type='L1Loss', loss_weight=5.0),
        obj_loss_iou=dict(type='GIoULoss', loss_weight=2.0),
        obj_loss_focal=dict(type='BCEFocalLoss', loss_weight=1.0),
        obj_loss_dice=dict(type='psgtrDiceLoss', loss_weight=1.0),
        rel_loss_cls=dict(type='CrossEntropyLoss',
                          use_sigmoid=False,
                          loss_weight=2.0,
                          class_weight=1.0)),
    train_cfg=dict(
        assigner=dict(
            type='MaskHTriMatcher',
            s_cls_cost=dict(type='ClassificationCost', weight=1.0),
            s_reg_cost=dict(type='BBoxL1Cost', weight=5.0),
            s_iou_cost=dict(type='IoUCost', iou_mode='giou', weight=2.0),
            s_focal_cost=dict(type='FocalLossCost',
                              weight=1.0, binary_input=True),
            s_dice_cost=dict(type='DiceCost', weight=1.0,
                             pred_act=True, eps=1.0),
            o_cls_cost=dict(type='ClassificationCost', weight=1.0),
            o_reg_cost=dict(type='BBoxL1Cost', weight=5.0),
            o_iou_cost=dict(type='IoUCost', iou_mode='giou', weight=2.0),
            o_focal_cost=dict(type='FocalLossCost',
                              weight=1.0, binary_input=True),
            o_dice_cost=dict(type='DiceCost', weight=1.0,
                             pred_act=True, eps=1.0),
            r_cls_cost=dict(type='ClassificationCost', weight=2.0),
        ),
        sampler=dict(type='PseudoSampler')),
    test_cfg=dict(max_per_image=100),
    init_cfg=None)
